options:
  collate: utf8_general_ci
  charset: utf8
  type: INNODB

Core_Model_Token:
  tableName: tokens
  actAs: [Timestampable, SoftDelete]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    hash:
      type: string(64)
      notnull: true
    service:
      type: string(255)
      notnull: true
    once:
      type: boolean
      default: 1
    jsoncontext:
      type: string

Core_Model_Preference:
  tableName: preferences
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    preference:
      type: string(64)
      notnull: true
    value:
      type: string(64)
    user_id:
      type: integer
  relations:
    User:
      class: User_Model_User
      local: user_id
      foreign: id