options:
  collate: utf8_general_ci
  charset: utf8
  type: INNODB

User_Model_User:
  tableName: users
  actAs: [Timestampable, SoftDelete]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    gender:
      type: enum
      values: ['female', 'male', 'nn']
    username:
      type: string(255)
    firstname:
      type: string(255)
    lastname:
      type: string(255)
    email:
      type: string(255)
      notnull: true
    language:
      type: string(5)
      default: en_GB
    password:
      type: string(255)
    salt:
      type: string(255)
    status:
      type: enum
      values: ['inactive', 'active', 'locked', 'deleted']
      default: 'inactive'
  relations:
<<<<<<< Updated upstream:application/configs/schema/schema.yml
      Preferences:
        class: User_Model_Preference
=======
    Preferences:
      class: Core_Model_Preference
    Roles:
      class: User_Model_Role
      local: id
      foreign: id
      refClass: User_Model_UserRole
>>>>>>> Stashed changes:application/configs/schema/user.yml

User_Model_Role:
  tableName: roles
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(64)
      notnull: true
<<<<<<< Updated upstream:application/configs/schema/schema.yml
=======
  relations:
    UserRoles:
      class: User_Model_UserRole
      local: id
      foreign: id
>>>>>>> Stashed changes:application/configs/schema/user.yml

User_Model_UserRole:
  columns:
    user_id:
      type: integer
      primary: true
    role_id:
      type: integer
      primary: true
  relations:
    User:
      class: User_Model_User
      local: user_id
<<<<<<< Updated upstream:application/configs/schema/schema.yml
    Role:
      class: User_Model_Role
      local: role_id

User_Model_Preference:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer
      notnull: true
    preference:
      type: string(64)
      notnull: true
    value:
      type: string(64)
    relations:
      User:
        class: User_Model_User
        local: user_id

Default_Model_Token:
  tableName: tokens
  actAs: [Timestampable, SoftDelete]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    hash:
      type: string(64)
      notnull: true
    service:
      type: string(255)
      notnull: true
    once:
      type: boolean
      default: 1
    jsoncontext:
      type: string
=======
      foreign: id
      foreignAlias: Roles
    Role:
      class: User_Model_Role
      local: role_id
      foreign: id
      foreignAlias: UserRoles
>>>>>>> Stashed changes:application/configs/schema/user.yml
