options:
  collate: utf8_general_ci
  charset: utf8
  type: INNODB

User:
  tableName: users
  actAs: [Timestampable, SoftDelete]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    gender:
      type: enum
      values: ['female', 'male', 'nn']
    username:
      type: string(255)
    firstname:
      type: string(255)
    lastname:
      type: string(255)
    email:
      type: string(255)
      notnull: true
    language:
      type: string(5)
      default: en_GB
    password:
      type: string(255)
    salt:
      type: string(255)
    status:
      type: enum
      values: ['inactive', 'active', 'locked', 'deleted']
      default: 'inactive'
    role:
      type: enum
      values: ['guest', 'user', 'admin']
      default: 'guest'
