<?php
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl(false, true);
header("Content-Type: text/html; charset=utf-8");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Patchwork</title>
        <link rel="shortcut icon" href="<?=$baseUrl?>/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="<?=$baseUrl?>/css/styles.css" />
        <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
        <?php
        echo $this->headScript()
        //->appendFile($baseUrl.'/js/jquery-1.3.2.min.js','text/javascript')
        ;
        ?>
        <script type="text/javascript">var base_url = '<?=$baseUrl?>';</script>
    </head>
    <body>
        <h1>Patchwork</h1>
        <?php echo $this->navigation()->menu()->render() ?>
        <div id="content">
            <div class="breadcrumbs">
            <?php
            echo $this->navigation()->breadcrumbs()->render();
            ?>
            </div>
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>