<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Patchwork</title>
        <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="/css/screen.css" />
        <?php
        echo $this->headScript()
        //->appendFile($baseUrl.'/js/jquery-1.3.2.min.js','text/javascript')
        ;
        ?>
        <script type="text/javascript">var base_url = '<?php echo $this->baseUrl() ?>';</script>
    </head>
    <body class="bp">

        <div id="container">
            <div id="header"><h1>Patchwork</h1></div>
            <div id="sidebar">
                <?php
                echo $this->navigation()->menu();
                ?>
            </div>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer">Patchwork <?php echo Patchwork::VERSION ?></div>
        </div>

    </body>
</html>