<?php

/**
 * User_Model_Base_UserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $role_id
 * @property User_Model_User $User_Model_User
 * @property User_Model_Role $User_Model_Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_UserRole extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_roles');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('User_Model_Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}