<?php

/**
 * User_Model_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Patchwork
 * @subpackage User
 * @author     Daniel Pozzi
 */
class User_Model_Role extends User_Model_Base_Role
{
    /**
     * to string
     * @return string
     */
    public function  __toString()
    {
        return (string)$this->name;
    }
}